/**
 * Placeholder art for dimensional wall lettering.
 *
 * The studio's product is raised lettering and word-cloud panels cut from
 * acrylic, PVC foam, MDF or aluminium, or 3D-printed, and mounted on the wall —
 * not printed pictures. So these placeholders draw objects that sit on a wall
 * and cast shadows, rather than images sitting inside a frame.
 *
 * Everything is drawn with alpha and no ground. A dimensional piece has no
 * rectangular substrate: the letters ARE the artwork and the wall behind them
 * belongs to the room. The site paints each piece's specified wall tone behind
 * it; AR puts it on the visitor's real wall, where a pale piece on a pale wall
 * correctly disappears — which is the reason wall tone is specified at all.
 *
 * Two font stacks, both confirmed present on the build machine by measuring
 * rendered ink rather than trusting the name. "Arial Black" is deliberately
 * absent: it resolves to plain Arial here, silently changing every metric.
 */

import METRICS from "./font-metrics.json" with { type: "json" };

/** Escape text for inclusion in SVG markup. */
const xml = (s) =>
  String(s).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[c],
  );

const between = (r, min, max) => min + r() * (max - min);
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));

/**
 * Measured metrics, not guessed. Rendering "THINK" at 130px and measuring the
 * ink box produced these ratios; they are what makes the fitting arithmetic
 * land inside the canvas rather than near it.
 */
export const FACES = {
  /** Condensed heavy display — what a dense word cloud is actually set in. */
  condensed: {
    key: "condensed",
    family: "Impact, Haettenschweiler, 'Arial Narrow', sans-serif",
    weight: 400,
  },
  /** Heavy geometric sans, for a single statement at monumental scale. */
  heavy: {
    key: "heavy",
    family: "'Segoe UI Black', 'Segoe UI', Tahoma, sans-serif",
    weight: 900,
  },
  /**
   * Serif italic, standing in for cut calligraphic letterforms.
   *
   * A calligraphy piece is letters, so the placeholder has to be letters. An
   * earlier version drew abstract flowing strokes and read as decoration
   * rather than writing — which misrepresents the one collection where the
   * words are the whole point.
   */
  script: {
    key: "script",
    family: "Georgia, 'Times New Roman', serif",
    weight: 700,
    style: "italic",
  },
};

/** Cap height as a fraction of the font size, measured per face. */
const capOf = (face) => METRICS[face.key].cap;

/**
 * Width of a string at a given size, summed from measured per-character
 * advances.
 *
 * A single average advance was not good enough and the failure was visible: the
 * mean for the heavy face is 0.68 but "W" is 1.07, so words like ANYWAY and
 * BETTER were fitted as if they were as narrow as THINK and ran off the canvas.
 * The table in font-metrics.json is generated by rendering each character eight
 * times and measuring the ink, so this is arithmetic rather than a guess.
 */
function textWidth(str, size, face, tracking = 0) {
  const m = METRICS[face.key];
  let total = 0;
  for (const ch of String(str)) {
    total += (m.widths[ch] ?? m.space) * size;
  }
  return total + Math.max(0, String(str).length - 1) * tracking;
}

/**
 * Emit one element as a physical raised object: a stack of offset copies in the
 * side colour reading as the cut edge, the face on top, and a contact shadow
 * beneath. `draw(dx, dy, colour, opacity)` returns the SVG for one layer.
 */
function raised(draw, { depth, stepX, stepY, side, face, shadow }) {
  let s = "";
  if (shadow) s += draw(shadow.x, shadow.y, shadow.colour, shadow.opacity);
  for (let i = depth; i >= 1; i -= 1) s += draw(stepX * i, stepY * i, side, 1);
  return s + draw(0, 0, face, 1);
}

/** A text layer factory suitable for `raised`. */
const textLayer = ({ x, y, size, face, tracking = 0, anchor = "middle", str }) =>
  (dx, dy, colour, opacity) =>
    `<text x="${(x + dx).toFixed(1)}" y="${(y + dy).toFixed(1)}" ` +
    `font-family="${face.family}" font-size="${size.toFixed(1)}" font-weight="${face.weight}" ` +
    `${face.style ? `font-style="${face.style}" ` : ""}` +
    `letter-spacing="${tracking.toFixed(2)}" text-anchor="${anchor}" fill="${colour}"` +
    `${opacity !== 1 ? ` opacity="${opacity}"` : ""}>${xml(str)}</text>`;

/** A path layer factory suitable for `raised`. `fill: "colour"` fills instead of strokes. */
const pathLayer = ({ d, strokeWidth, cap = "round", fill = "none" }) =>
  (dx, dy, colour, opacity) =>
    `<path d="${d}" transform="translate(${dx.toFixed(1)} ${dy.toFixed(1)})" ` +
    `fill="${fill === "colour" ? colour : fill}" ` +
    `stroke="${fill === "colour" ? "none" : colour}" ` +
    `stroke-width="${strokeWidth.toFixed(1)}" stroke-linecap="${cap}" stroke-linejoin="round"` +
    `${opacity !== 1 ? ` opacity="${opacity}"` : ""}/>`;

/** Depth scaled to the canvas, so a small piece is not drawn with a giant edge. */
const depthFor = (w) => {
  const step = Math.max(1.5, w * 0.0035);
  return { depth: 6, stepX: step, stepY: step, shadowOffset: step * 7 };
};

/** A full circle as a single arc — `a r r 0 1 0 0.01 0` closes on itself. */
const circlePath = (cx, cy, r) => `M ${cx} ${cy - r} a ${r} ${r} 0 1 0 0.01 0 z`;

/* ------------------------------------------------------------------------- */
/* 1. Word cloud packed into a lightbulb                                      */
/* ------------------------------------------------------------------------- */

/**
 * Words packed into a lightbulb silhouette with one hero word across the middle.
 *
 * Rows are measured against the actual chord of the glass at each height, so
 * the cloud takes the bulb's shape instead of being a rectangle with the
 * corners knocked off.
 */
export function wordCloudBulb(r, w, h, p, { words, hero }) {
  const { depth, stepX, stepY, shadowOffset } = depthFor(w);
  const face = FACES.condensed;
  let s = "";

  /**
   * Deal words without replacement, refilling only when the pool runs dry, and
   * never repeat the hero word among them. Picking at random with replacement
   * put the same word three times in one bulb, which reads as a fault rather
   * than as a composition.
   */
  const pool = words.filter((x) => x.toUpperCase() !== String(hero).toUpperCase());
  let bag = [];
  const deal = () => {
    if (!bag.length) {
      bag = [...pool];
      // Fisher-Yates, seeded from the same PRNG so the piece stays deterministic.
      for (let i = bag.length - 1; i > 0; i -= 1) {
        const j = Math.floor(r() * (i + 1));
        [bag[i], bag[j]] = [bag[j], bag[i]];
      }
    }
    return bag.pop();
  };

  const cx = w / 2;
  const glassR = Math.min(w * 0.45, h * 0.30);
  const cy = glassR + h * 0.045;
  const neckTop = cy + glassR * 0.8;
  const neckBottom = cy + glassR * 1.3;
  const baseTop = neckBottom;
  const baseH = h * 0.16;

  /** Half-width of the silhouette at a given height. */
  const halfWidthAt = (y) => {
    if (y <= cy + glassR) {
      const dy = Math.abs(y - cy);
      return dy >= glassR ? 0 : Math.sqrt(glassR * glassR - dy * dy);
    }
    const t = clamp((y - neckTop) / (neckBottom - neckTop), 0, 1);
    return glassR * (0.62 - 0.3 * t);
  };

  const heroSize = Math.min((glassR * 2 * 0.86) / textWidth(hero, 1, face), h * 0.22);
  const heroBandTop = cy - heroSize * 0.55;
  const heroBandBottom = cy + heroSize * 0.55;

  const rows = [];
  let y = cy - glassR + h * 0.012;
  while (y < neckBottom) {
    const rowH = between(r, h * 0.03, h * 0.052);
    const mid = y + rowH * 0.5;
    if (mid > heroBandTop - rowH * 0.3 && mid < heroBandBottom + rowH * 0.3) {
      y = heroBandBottom + rowH * 0.32;
      continue;
    }
    const available = halfWidthAt(mid) * 2 * 0.94;
    if (available > w * 0.06) rows.push({ mid, rowH, available });
    y += rowH * 1.04;
  }

  for (const row of rows) {
    const size = row.rowH / capOf(face);
    const gap = size * 0.26;
    const chosen = [];
    let used = 0;
    // Try several candidates per slot: a word that does not fit should not end
    // the row when a shorter one still would. Give up after enough misses.
    let misses = 0;
    const rejected = [];
    while (misses < 6 && chosen.length < 6) {
      const word = deal();
      const wd = textWidth(word, size, face);
      const needed = used + wd + (chosen.length ? gap : 0);
      if (needed > row.available) {
        // Too wide for what is left of this row, but still unused — hold it and
        // return it to the bag rather than dropping it from the piece.
        rejected.push(word);
        misses += 1;
        continue;
      }
      used = needed;
      chosen.push({ word, wd });
    }
    bag.push(...rejected);
    if (!chosen.length) continue;
    let x = cx - used / 2;
    for (const { word, wd } of chosen) {
      s += raised(
        textLayer({ x: x + wd / 2, y: row.mid + row.rowH * 0.5, size, face, str: word }),
        {
          depth,
          stepX,
          stepY,
          side: p.side,
          face: p.face,
          shadow: { x: shadowOffset, y: shadowOffset, colour: p.shadow, opacity: 0.3 },
        },
      );
      x += wd + gap;
    }
  }

  // The hero word, in the accent, standing proud of everything around it.
  s += raised(
    textLayer({ x: cx, y: cy + heroSize * capOf(face) * 0.5, size: heroSize, face, str: hero }),
    {
      depth: depth + 3,
      stepX,
      stepY,
      side: p.accentSide,
      face: p.accent,
      shadow: { x: shadowOffset * 1.3, y: shadowOffset * 1.3, colour: p.shadow, opacity: 0.34 },
    },
  );

  // Screw base: three bands and a tip, in the accent.
  const accentRaise = {
    depth,
    stepX,
    stepY,
    side: p.accentSide,
    face: p.accent,
    shadow: { x: shadowOffset, y: shadowOffset, colour: p.shadow, opacity: 0.28 },
  };
  const bandW = glassR * 0.62;
  for (let i = 0; i < 3; i += 1) {
    const by = baseTop + baseH * (0.06 + i * 0.24);
    const bh = baseH * 0.17;
    s += raised(
      pathLayer({
        d:
          `M ${cx - bandW / 2} ${by} h ${bandW} ` +
          `a ${bh / 2} ${bh / 2} 0 0 1 0 ${bh} h ${-bandW} ` +
          `a ${bh / 2} ${bh / 2} 0 0 1 0 ${-bh} z`,
        strokeWidth: 0,
        fill: "colour",
      }),
      accentRaise,
    );
  }
  const tipTop = baseTop + baseH * 0.78;
  s += raised(
    pathLayer({
      d:
        `M ${cx - bandW * 0.34} ${tipTop} L ${cx + bandW * 0.34} ${tipTop} ` +
        `L ${cx + bandW * 0.16} ${tipTop + baseH * 0.22} ` +
        `L ${cx - bandW * 0.16} ${tipTop + baseH * 0.22} z`,
      strokeWidth: 0,
      fill: "colour",
    }),
    accentRaise,
  );

  return s;
}

/* ------------------------------------------------------------------------- */
/* 2. A single statement at monumental scale                                  */
/* ------------------------------------------------------------------------- */

/**
 * One line stacked into words, optionally carrying the noughts-and-crosses
 * motif that the "think outside the box" pieces are built around.
 */
export function statementLines(r, w, h, p, { title, motif }) {
  const { depth, stepX, stepY, shadowOffset } = depthFor(w);
  const face = FACES.heavy;
  const words = String(title)
    .replace(/[^A-Za-z0-9' ]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .map((x) => x.toUpperCase());
  if (!words.length) return "";

  const motifH = motif ? h * 0.3 : 0;
  const blockH = h - motifH - h * 0.14;
  const maxWidth = w * 0.84;

  /**
   * Choose the line breaks that let the type be largest.
   *
   * One word per line is right for a portrait and wrong for a panorama: three
   * stacked words in a 5:2 box are each a third of the height, and they ran off
   * the bottom. So every split from one line up to one-word-per-line is costed
   * against both the width and the height, and the biggest that fits wins.
   */
  const layoutFor = (lineCount) => {
    const perLine = Math.ceil(words.length / lineCount);
    const lines = [];
    for (let i = 0; i < words.length; i += perLine) {
      lines.push(words.slice(i, i + perLine).join(" "));
    }
    const widest = Math.max(...lines.map((line) => textWidth(line, 1, face)));
    const size = Math.min(maxWidth / widest, blockH / (lines.length * 1.14));
    return { lines, size };
  };

  let best = layoutFor(1);
  for (let n = 2; n <= words.length; n += 1) {
    const candidate = layoutFor(n);
    if (candidate.size > best.size) best = candidate;
  }
  const { lines, size } = best;
  const lineH = size * 1.14;
  const left = w * 0.08;
  let y = h * 0.07 + size * capOf(face);

  const faceRaise = (extra = 0, accent = false, shadowScale = 1) => ({
    depth: Math.max(3, depth + extra),
    stepX,
    stepY,
    side: accent ? p.accentSide : p.side,
    face: accent ? p.accent : p.face,
    shadow: {
      x: shadowOffset * shadowScale,
      y: shadowOffset * shadowScale,
      colour: p.shadow,
      opacity: 0.3,
    },
  });

  let s = "";
  for (const line of lines) {
    s += raised(textLayer({ x: left, y, size, face, anchor: "start", str: line }), faceRaise());
    y += lineH;
  }

  if (motif) {
    const gridTop = h - motifH - h * 0.02;
    const gridSize = Math.min(w * 0.62, motifH);
    const gx = left;
    const cell = gridSize / 3;
    const bar = Math.max(4, gridSize * 0.028);

    for (let i = 1; i <= 2; i += 1) {
      s += raised(
        pathLayer({ d: `M ${gx + cell * i} ${gridTop} V ${gridTop + gridSize}`, strokeWidth: bar }),
        faceRaise(-2, false, 0.7),
      );
      s += raised(
        pathLayer({ d: `M ${gx} ${gridTop + cell * i} H ${gx + gridSize}`, strokeWidth: bar }),
        faceRaise(-2, false, 0.7),
      );
    }

    const marks = ["O", "X", "X", "X", "O", "O", "X", "O", "X"];
    const glyph = cell * 0.62;
    for (let i = 0; i < 9; i += 1) {
      const gcx = gx + cell * (i % 3) + cell / 2;
      const gcy = gridTop + cell * Math.floor(i / 3) + cell / 2;
      const d =
        marks[i] === "O"
          ? circlePath(gcx, gcy, glyph / 2)
          : `M ${gcx - glyph / 2} ${gcy - glyph / 2} L ${gcx + glyph / 2} ${gcy + glyph / 2} ` +
            `M ${gcx + glyph / 2} ${gcy - glyph / 2} L ${gcx - glyph / 2} ${gcy + glyph / 2}`;
      s += raised(pathLayer({ d, strokeWidth: bar * 0.9 }), faceRaise(-2, false, 0.6));
    }

    // The winning line struck through the grid, breaking it in the accent.
    s += raised(
      pathLayer({
        d: `M ${gx + cell * 1.5} ${gridTop - gridSize * 0.06} V ${gridTop + gridSize * 1.06}`,
        strokeWidth: bar * 1.5,
      }),
      faceRaise(0, true),
    );
  }

  return s;
}

/* ------------------------------------------------------------------------- */
/* 3. Outline line-art bulbs on wires                                         */
/* ------------------------------------------------------------------------- */

/**
 * Bulbs drawn as continuous outline on hanging wires, each carrying one word.
 * Stroke only, never filled: these are printed as a filament line, and a solid
 * shape would misrepresent what arrives.
 */
export function lineArtBulbs(r, w, h, p, { words }) {
  // The word inside the ring is set condensed, not in the heavy face: at six
  // bulbs across a wall these are the only legible option — the heavy face put
  // "INNOVATION" at a fifth of the ring's width and it read as a smudge.
  const face = FACES.condensed;
  const step = Math.max(1.2, w * 0.0022);
  const n = clamp(words.length, 4, 6);
  const slot = w / n;
  const stroke = Math.max(3, w * 0.0095);
  let s = "";

  for (let i = 0; i < n; i += 1) {
    const colour = p.line[i % p.line.length];
    const side = p.lineSide[i % p.lineSide.length];
    const cx = slot * (i + 0.5);
    // Alternating drops so the row reads as hung rather than ruled.
    const drop = h * (i % 2 === 0 ? 0.34 : 0.52);
    const bulbR = Math.min(slot * 0.42, h * 0.17);
    const bulbCy = drop + bulbR * 1.15;

    const wire =
      `M ${cx} 0 C ${cx + slot * 0.12} ${drop * 0.3}, ` +
      `${cx - slot * 0.12} ${drop * 0.62}, ${cx} ${drop}`;
    const coil = Array.from({ length: 4 }, (_, k) => {
      const cyk = drop + (bulbR * 0.28 * k) / 2;
      return `M ${cx - bulbR * 0.3} ${cyk} q ${bulbR * 0.3} ${bulbR * 0.16}, ${bulbR * 0.6} 0`;
    }).join(" ");
    const glass = circlePath(cx, bulbCy, bulbR);

    const drawGroup = (dx, dy, c, opacity) =>
      `<g transform="translate(${dx.toFixed(1)} ${dy.toFixed(1)})" fill="none" stroke="${c}" ` +
      `stroke-width="${stroke.toFixed(1)}" stroke-linecap="round"` +
      `${opacity !== 1 ? ` opacity="${opacity}"` : ""}>` +
      `<path d="${wire}"/><path d="${coil}"/><path d="${glass}"/></g>`;

    s += raised(drawGroup, {
      depth: 4,
      stepX: step,
      stepY: step,
      side,
      face: colour,
      shadow: { x: step * 6, y: step * 6, colour: p.shadow, opacity: 0.26 },
    });

    const word = words[i % words.length].toUpperCase();
    const size = Math.min((bulbR * 1.7) / textWidth(word, 1, face), bulbR * 0.5);
    s += raised(
      textLayer({ x: cx, y: bulbCy + size * capOf(face) * 0.5, size, face, str: word }),
      {
        depth: 3,
        stepX: step,
        stepY: step,
        side,
        face: colour,
        shadow: { x: step * 4, y: step * 4, colour: p.shadow, opacity: 0.22 },
      },
    );
  }
  return s;
}

/* ------------------------------------------------------------------------- */
/* 4. Raised calligraphic stroke                                              */
/* ------------------------------------------------------------------------- */

/**
 * A word cut as calligraphic letterforms, mounted proud of the wall, with an
 * underswept flourish. The word carries the piece; the flourish is trim.
 */
export function raisedScript(r, w, h, p, { word }) {
  const { depth, stepX, stepY, shadowOffset } = depthFor(w);
  const face = FACES.script;
  const text = String(word).trim() || "Sabr";
  const cx = w / 2;
  let s = "";

  const size = Math.min((w * 0.78) / textWidth(text, 1, face), h * 0.34);
  const baseline = h * 0.5 + size * capOf(face) * 0.3;

  s += raised(textLayer({ x: cx, y: baseline, size, face, str: text }), {
    depth: depth + 2,
    stepX,
    stepY,
    side: p.side,
    face: p.face,
    shadow: { x: shadowOffset * 1.2, y: shadowOffset * 1.2, colour: p.shadow, opacity: 0.32 },
  });

  // A single sweep under the word, in the accent, echoing a pen's exit stroke.
  const half = (textWidth(text, size, face) / 2) * 1.06;
  s += raised(
    pathLayer({
      d:
        `M ${cx - half} ${baseline + size * 0.24} ` +
        `C ${cx - half * 0.3} ${baseline + size * 0.42}, ` +
        `${cx + half * 0.3} ${baseline + size * 0.1}, ` +
        `${cx + half} ${baseline + size * 0.3}`,
      strokeWidth: size * 0.075,
    }),
    {
      depth,
      stepX,
      stepY,
      side: p.accentSide,
      face: p.accent,
      shadow: { x: shadowOffset, y: shadowOffset, colour: p.shadow, opacity: 0.28 },
    },
  );

  const dotR = size * 0.055;
  s += raised(
    pathLayer({
      d: circlePath(cx + half * 0.5, baseline - size * 0.92, dotR),
      strokeWidth: 0,
      fill: "colour",
    }),
    {
      depth,
      stepX,
      stepY,
      side: p.accentSide,
      face: p.accent,
      shadow: { x: shadowOffset, y: shadowOffset, colour: p.shadow, opacity: 0.28 },
    },
  );
  return s;
}

/* ------------------------------------------------------------------------- */
/* 5. A composed group of value words                                         */
/* ------------------------------------------------------------------------- */

/** Values or team words as one composed group, with a single word in the accent. */
export function valuesBoard(r, w, h, p, { words }) {
  const { depth, stepX, stepY, shadowOffset } = depthFor(w);
  const face = FACES.heavy;
  const list = words.slice(0, 6).map((x) => x.toUpperCase());
  const rowH = (h * 0.82) / list.length;
  const heroIndex = Math.floor(r() * list.length);
  let s = "";

  list.forEach((word, i) => {
    const isHero = i === heroIndex;
    const target = w * (isHero ? 0.86 : between(r, 0.52, 0.74));
    const size = Math.min(target / textWidth(word, 1, face), rowH * 0.74);
    const alignLeft = i % 2 === 0;
    s += raised(
      textLayer({
        x: alignLeft ? w * 0.08 : w * 0.92,
        y: h * 0.11 + rowH * i + size * capOf(face),
        size,
        face,
        anchor: alignLeft ? "start" : "end",
        str: word,
      }),
      {
        depth: isHero ? depth + 2 : depth,
        stepX,
        stepY,
        side: isHero ? p.accentSide : p.side,
        face: isHero ? p.accent : p.face,
        shadow: { x: shadowOffset, y: shadowOffset, colour: p.shadow, opacity: 0.3 },
      },
    );
  });
  return s;
}

/* ------------------------------------------------------------------------- */
/* 6. Brand wall — mark, wordmark, rule                                       */
/* ------------------------------------------------------------------------- */

/** A logo wall: abstract mark, wordmark and rule, all cut and mounted. */
export function brandWall(r, w, h, p, { title }) {
  const { depth, stepX, stepY, shadowOffset } = depthFor(w);
  const face = FACES.heavy;
  const word =
    String(title).replace(/[^A-Za-z0-9 ]/g, "").toUpperCase().trim() || "STUDIO";
  const cx = w / 2;
  let s = "";

  const mark = (d, accent) =>
    raised(pathLayer({ d, strokeWidth: Math.min(w * 0.17, h * 0.13) * 0.3 }), {
      depth,
      stepX,
      stepY,
      side: accent ? p.accentSide : p.side,
      face: accent ? p.accent : p.face,
      shadow: { x: shadowOffset, y: shadowOffset, colour: p.shadow, opacity: 0.3 },
    });

  const markR = Math.min(w * 0.17, h * 0.13);
  const markCy = h * 0.3;
  s += mark(`M ${cx - markR} ${markCy} a ${markR} ${markR} 0 0 1 ${markR * 2} 0`, false);
  s += mark(
    `M ${cx - markR * 0.52} ${markCy + markR * 0.52} ` +
      `a ${markR * 0.52} ${markR * 0.52} 0 0 0 ${markR * 1.04} 0`,
    true,
  );

  const size = Math.min((w * 0.8) / textWidth(word, 1, face, 0), h * 0.11);
  s += raised(
    textLayer({ x: cx, y: h * 0.6, size, face, tracking: size * 0.06, str: word }),
    {
      depth,
      stepX,
      stepY,
      side: p.side,
      face: p.face,
      shadow: { x: shadowOffset, y: shadowOffset, colour: p.shadow, opacity: 0.32 },
    },
  );

  s += raised(
    pathLayer({
      d: `M ${w * 0.3} ${h * 0.7} H ${w * 0.7}`,
      strokeWidth: h * 0.01,
      cap: "butt",
    }),
    {
      depth: Math.max(3, depth - 2),
      stepX,
      stepY,
      side: p.accentSide,
      face: p.accent,
      shadow: { x: shadowOffset * 0.7, y: shadowOffset * 0.7, colour: p.shadow, opacity: 0.26 },
    },
  );
  return s;
}
